# Actionsの使用を開始するのに役立つ基本的なワークフローです

name: CI

# ワークフローが実行される時間を制御します
on:
  # "main"ブランチの場合のみプッシュまたはプルリクエストイベント時にワークフローをトリガーします
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Actionsタブからこのワークフローを手動で実行できるようにします
  workflow_dispatch:

# ワークフロー実行は、順序に実行されるか並列で実行される1つ以上のジョブで構成されます
jobs:
  # このワークフローには"build"という名前の単一ジョブが含まれています
  build:
    # ジョブが実行されるランナーのタイプ
    runs-on: ubuntu-latest

    # ステップはジョブの一部として実行されるタスクのシーケンスを表します
    steps:
      # $GITHUB_WORKSPACEの下であなたのリポジトリをチェックアウトして、ジョブがそれにアクセスできるようにします
      - uses: actions/checkout@v4

      # ランナーのシェルを使用して単一のコマンドを実行します
      - name: Run a one-line script
        run: echo Hello, world!

      # ランナーのシェルを使用してコマンドセットを実行します
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
